const disneyCharactersArray = ["Abby",
    "Abigail",
    "Abu",
    "Achilles",
    "Adelaide",
    "Adella",
    "Adorabeezle",
    "Ajax",
    "Akela",
    "Aladar",
    "Aladdin",
    "Alameda",
    "Alana",
    "Alcmene",
    "Albus",
    "Alfonso",
    "Alice",
    "Amelia",
    "Amity",
    "Amos",
    "Anastasia",
    "Andrina",
    "Angus",
    "Apollo",
    "Aquata",
    "Assistant Mayor Dawn Bellwether",
    "Arlo",
    "Atka",
    "Augustus",
    "Aurora",
    "Babette",
    "Bagheera",
    "Baloo",
    "Bambi",
    "Banzai",
    "Baylene",
    "Beaker",
    "Beatrice",
    "Beaver",
    "Belle",
    "Bert",
    "Bolt",
    "Boone",
    "Bruce",
    "Buck",
    "Bullseye",
    "Bruni",
    "Bruno",
    "Buster",
    "Buzz",
    "Captain Hook",
    "Charles",
    "Charlotte",
    "Chernabog",
    "Chief",
    "Chien-Po",
    "Chip",
    "Chuck",
    "Cinderella",
    "Clayton",
    "Cleo",
    "Clio",
    "Clover",
    "Coco",
    "Cody",
    "Colette",
    "Cookie",
    "Copper",
    "Count Frollo",
    "Cruella",
    "Daisy",
    "Dante",
    "Darla",
    "Dewey",
    "Dinah",
    "Dodger",
    "Donald",
    "Dopey",
    "Dory",
    "Drizella",
    "Duchess",
    "Duey",
    "Eeyore",
    "Elsa",
    "Eric",
    "Enesto",
    "Esmeralda",
    "Evil Queen",
    "Fa Zhou",
    "Fairy Godmother",
    "Figaro",
    "Flit",
    "Flora",
    "Flounder",
    "Flynn",
    "Gaston",
    "George Banks",
    "Geppetto",
    "Gideon",
    "Goofy",
    "Hamm",
    "Hector",
    "Hei Hei",
    "Hercules",
    "Hewey",
    "Horace",
    "Imelda",
    "Jane",
    "Jane Banks",
    "Jaq",
    "Jasmine",
    "Jasper",
    "Jessie",
    "Jim Hawkins",
    "Jimmy",
    "John Smith",
    "Kaa",
    "Kessie",
    "Kuzco",
    "Lady",
    "Lady Kluck",
    "Li Shang",
    "Lilo",
    "Ling",
    "Linguini",
    "Louie",
    "Lucky",
    "Mal",
    "Mary Poppins",
    "Mad Hatter",
    "March Hare",
    "Marlin",
    "Maui",
    "Max",
    "Meeko",
    "Merida",
    "Merryweather",
    "Mickey",
    "Michael Banks",
    "Mim",
    "Minnie",
    "Moana",
    "Mowgli",
    "Mrs. Potts",
    "Mufasa",
    "Mulan",
    "Mushu",
    "Nala",
    "Nana",
    "Naveen",
    "Nemo",
    "Nora",
    "Pacha",
    "Patch",
    "Pegasus",
    "Perdita",
    "Phoebus",
    "Pluto",
    "Pocahontas",
    "Pongo",
    "Prudence",
    "Pua",
    "Pumbaa",
    "Quasimodo",
    "Queen of Hearts",
    "Remy",
    "Rolly",
    "Roo",
    "Simba",
    "Slink",
    "Snow",
    "Stella",
    "Stitch",
    "Tala",
    "Tamatoa",
    "Terk",
    "Thumper",
    "Tiana",
    "Tigger",
    "Timon",
    "Tinker Bell",
    "Tito",
    "Toby",
    "Tod",
    "Triton",
    "Tui",
    "Ursula",
    "Vixey",
    "Wally",
    "Willow",
    "Winnie",
    "Woody"]

 // from all over the web 
 // indexes match the movie names in disneyMoviesArray.js
 console.log("disneyMovieArray loaded...");