const disneyMoviesArray = [
    "Chicken Little",
    "The Aristocats",
    "Aladdin",
    "The Hunchback of Notre Dame",
    "The Aristocats",
    "The Little Mermaid",
    "Wreck-It Ralph",
    "Donald Duck and the Gorilla",
    "The Jungle Book",
    "Dinosaur",
    "Aladdin",
    "Home on the Range",
    "The Little Mermaid",
    "Hercules",
    "Amphibia",
    "Star vs. The Forces of Evil",
    "Alice in Wonderland",
    "The Aristocats",
    "The Owl House",
    "The Fox and the Hound",
    "Cinderella",
    "The Little Mermaid",
    "The Adventures of Ichabod and Mr. Toad",
    "Hercules",
    "The Little Mermaid ",
    "Zootopia",
    "The Good Dinosaur",
    "Brother Bear 2",
    "The Owl House",
    "Sleeping Beauty",
    "Beauty and the Beast",
    "The Jungle Book",
    "The Jungle Book",
    "Bambi",
    "The Lion King",
    "Dinosaur",
    "Muppet Babies",
    "Cinderella",
    "Lady and the Tramp",
    "Beauty and the Beast",
    "Mary Poppins",
    "Bolt",
    "Penn Zero: Part-Time Hero",
    "Finding Nemo",
    "Home on the Range",
    "Toy Story 2",
    "Frozen II",
    "Cinderella",
    "Lady and the Tramp",
    "Toy Story",
    "Peter Pan",
    "UP",
    "The Princess and the Frog",
    "Fantasia",
    "The Fox and the Hound",
    "Mulan",
    "Beauty and the Beast",
    "Amphibia",
    "Cinderella",
    "Tarzan",
    "Pinocchio",
    "Hercules",
    "Sofia the First",
    "Coco",
    "The Rescuers Down Under",
    "Lady and the Tramp II: Scamp’s Adventure",
    "Atlantis: The Lost Empire",
    "The Fox and the Hound",
    "The Hunchback of Notre Dame",
    "101 Dalmatians",
    "Classic Disney cartoons",
    "Coco",
    "Finding Nemo",
    "Mickey Mouse Universe",
    "Alice in Wonderland",
    "Oliver & Company",
    "Mickey Mouse Universe",
    "Snow White and the Seven Dwarfs",
    "Finding Nemo",
    "Cinderella",
    "The Aristocats",
    "DuckTales",
    "Winnie the Pooh",
    "Frozen",
    "The Little Mermaid",
    "Coco",
    "The Hunchback of Notre Dame",
    "Snow White and the Seven Dwarves",
    "Mulan",
    "Cinderella",
    "Pinocchio",
    "Pocahontas",
    "Sleeping Beauty",
    "The Little Mermaid",
    "Tangled",
    "Beauty and the Beast",
    "Mary Poppins",
    "Pinocchio",
    "Pinocchio",
    "Classic Disney cartoons",
    "Toy Story",
    "Coco",
    "Moana",
    "Hercules",
    "DuckTales",
    "101 Dalmatians",
    "Coco",
    "Tarzan",
    "Mary Poppins",
    "Cinderella",
    "Aladdin",
    "101 Dalmatians",
    "Toy Story 2",
    "Treasure Planet",
    "Pinocchio",
    "Pocahantas",
    "The Jungle Book",
    "Winnie the Pooh",
    "The Emperor’s New Groove",
    "Lady and the Tramp",
    "Robin Hood",
    "Mulan",
    "Lilo & Stitch",
    "Mulan",
    "Ratatouille",
    "DuckTales",
    "101 Dalmatians",
    "The Descendants",
    "Mary Poppins",
    "Alice in Wonderland",
    "Alice in Wonderland",
    "Finding Nemo",
    "Moana",
    "The Little Mermaid",
    "Pocahontas",
    "Brave",
    "Sleeping Beauty",
    "Classic Disney cartoons",
    "Mary Poppins",
    "The Sword in the Stone",
    "Classic Disney cartoons",
    "Moana",
    "The Jungle Book",
    "Beauty and the Beast",
    "The Lion King",
    "Mulan",
    "Mulan",
    "The Lion King",
    "Peter Pan",
    "The Princess and the Frog",
    "Finding Nemo",
    "Pete’s Dragon",
    "The Emperor’s New Groove",
    "101 Dalmatians",
    "Hercules",
    "101 Dalmatians",
    "The Hunchback of Notre Dame",
    "Classic Disney cartoons",
    "Pocahontas",
    "101 Dalmatians",
    "Cinderella",
    "Moana",
    "The Lion King",
    "The Hunchback of Notre Dame",
    "Alice in Wonderland",
    "Ratatouille",
    "101 Dalmatians",
    "Winnie the Pooh",
    "The Lion King",
    "Toy Story",
    "Snow White and the Seven Dwarfs",
    "The Princess and the Frog",
    "Lilo & Stitch",
    "Moana",
    "Moana",
    "Tarzan",
    "Bambi",
    "The Princess and the Frog",
    "Winnie the Pooh",
    "The Lion King",
    "Peter Pan",
    "Oliver & Company",
    "The Great Mouse Detective",
    "The Fox and the Hound",
    "The Little Mermaid",
    "Moana",
    "The Little Mermaid",
    "The Fox and the Hound",
    "101 Dalmatians",
    "Pocahontas",
    "Winnie the Pooh",
    "Toy Story"
  ]

// from all over the web 
 // indexes match the character names in disneyCharactersArray.js
 console.log("disneyMovieArray loaded...");